# Gemvis one-click setup for Windows PowerShell.
# Run: .\scripts\setup_windows.ps1  (or double-click scripts\setup_windows.bat)

$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Step($msg) { Write-Host "`n=== $msg ===" -ForegroundColor Cyan }
function Ok($msg)   { Write-Host "   [OK]   $msg" -ForegroundColor Green }
function Warn($msg) { Write-Host "   [WARN] $msg" -ForegroundColor Yellow }
function Fail($msg) { Write-Host "`n   [FAIL] $msg" -ForegroundColor Red; Read-Host "`nPress Enter to exit"; exit 1 }
function Have($cmd) { return [bool](Get-Command $cmd -ErrorAction SilentlyContinue) }

function Refresh-Path {
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" +
                [System.Environment]::GetEnvironmentVariable("Path","User")
}

function Install-Winget-Package {
    param([string]$Id, [string]$Name)
    Write-Host "   Installing $Name via winget (this may take 1-2 minutes) ..."
    try {
        # Force winget source to avoid msstore certificate errors
        winget install --id $Id --source winget --accept-source-agreements --accept-package-agreements --silent
    } catch {
        Warn "winget install failed: $_"
    }
    Refresh-Path
}

Write-Host "Gemvis setup starting (Windows PowerShell)" -ForegroundColor Cyan
Refresh-Path

# ---- Pre-check: Git ----
if (-not (Have "git")) {
    Write-Host "`n[FAIL] Git not found." -ForegroundColor Red
    Write-Host "   Installing Git ..." -ForegroundColor Yellow
    Install-Winget-Package "Git.Git" "Git"
    if (-not (Have "git")) {
        Fail "Git installation failed. Please install manually: https://git-scm.com/download/win`n   Then restart PowerShell and re-run setup."
    }
}
Ok "git detected: $((Get-Command git).Source)"

# ---- 1. .env ----
Step "1/4  Create .env"
if (-not (Test-Path ".env")) {
    @"
# Gemvis environment - generated by setup_windows.ps1
LLM_BASE_URL=http://127.0.0.1:8080/v1
LLM_API_KEY=none
LLM_MODEL=unsloth/gemma-4-E2B-it-GGUF:Q4_K_M

GEMVIS_WATCH_DIR=$($env:USERPROFILE)\gemvis_watch
"@ | Out-File -FilePath ".env" -Encoding utf8 -NoNewline
    Ok ".env created"
} else {
    # Validate GEMVIS_WATCH_DIR format - convert Git Bash style (/c/Users/...) to Windows
    $changed = $false
    $newLines = Get-Content .env | ForEach-Object {
        if ($_ -match "^(GEMVIS_WATCH_DIR=)(/([a-zA-Z])/.+)$") {
            $drive = $matches[3].ToUpper()
            $rest  = $matches[2].Substring(3) -replace "/", "\"
            $changed = $true
            "$($matches[1])${drive}:\$rest"
        } else {
            $_
        }
    }
    if ($changed) {
        $newLines | Out-File -FilePath .env -Encoding utf8
        Ok ".env GEMVIS_WATCH_DIR converted to Windows format"
    } else {
        Ok ".env already exists (verified)"
    }
}
$watchDir = "$env:USERPROFILE\gemvis_watch"
New-Item -ItemType Directory -Force -Path $watchDir | Out-Null
Ok "Watch directory ready: $watchDir"

# ---- 2. Python venv ----
Step "2/4  Python venv + dependencies"

# Check Python version (3.11 recommended for rdflib/pyparsing compatibility)
$pythonCmd = "python"
if (Have "python3.11") {
    $pythonCmd = "python3.11"
    Ok "Python 3.11 detected (recommended)"
} elseif (Have "python") {
    $pyVer = & python --version 2>&1 | Select-String -Pattern "(\d+\.\d+)" | ForEach-Object { $_.Matches.Groups[1].Value }
    if ($pyVer -eq "3.13" -or $pyVer -eq "3.14") {
        Warn "Python $pyVer detected - may have compatibility issues with rdflib"
        Warn "Installing Python 3.11 (recommended) ..."
        Install-Winget-Package "Python.Python.3.11" "Python 3.11"
        if (Have "python3.11") {
            $pythonCmd = "python3.11"
            Ok "Python 3.11 installed"
        }
    }
} else {
    Write-Host "`n[FAIL] Python not found." -ForegroundColor Red
    Write-Host "   Installing Python 3.11 ..." -ForegroundColor Yellow
    Install-Winget-Package "Python.Python.3.11" "Python 3.11"
    Refresh-Path
    if (Have "python3.11") {
        $pythonCmd = "python3.11"
        Ok "Python 3.11 installed"
    } elseif (Have "python") {
        $pythonCmd = "python"
        Ok "Python installed (version may vary)"
    } else {
        Fail "Python installation failed. Please install manually: https://www.python.org/downloads/`n   Then restart PowerShell and re-run setup."
    }
}

if (-not (Test-Path "venv")) {
    & $pythonCmd -m venv venv
    Ok "venv created with $pythonCmd"
} else {
    Ok "venv exists"
}

$venvPython = ".\venv\Scripts\python.exe"
Write-Host "   Upgrading pip ..."
& $venvPython -m pip install --upgrade pip
Write-Host "   Installing requirements.txt (this takes 1-3 minutes; sentence-transformers ~120MB) ..."
& $venvPython -m pip install -r requirements.txt
Ok "Backend dependencies installed"

# ---- 3. llama.cpp ----
Step "3/4  llama.cpp"
if (Have "llama-server") {
    Ok "llama-server already installed: $((Get-Command llama-server).Source)"
} else {
    Install-Winget-Package "ggml.llamacpp" "llama.cpp"
    if (Have "llama-server") {
        Ok "llama.cpp installed"
    } else {
        Warn "llama-server not in PATH yet. Open a new PowerShell window and re-run setup."
        Warn "   Or continue setup and manually add llama-server to PATH."
    }
}

# ---- 4. Frontend ----
Step "4/4  Frontend build"
if (-not (Have "npm")) {
    Install-Winget-Package "OpenJS.NodeJS.LTS" "Node.js LTS"
}

if (Have "npm") {
    Push-Location frontend
    try {
        Write-Host "   Running npm install (1-3 minutes) ..."
        npm install --silent
        Write-Host "   Running npm run build ..."
        npm run build
        Ok "frontend\dist\ build complete"
    } catch {
        Warn "Frontend build failed (backend can still work without it)"
    } finally {
        Pop-Location
    }
} else {
    Warn "npm still not in PATH. Open a new PowerShell and re-run (backend can still work without it)."
}

Write-Host "`n=================================================" -ForegroundColor Green
Write-Host "Gemvis setup complete" -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Green
Write-Host "`nNext step:"
Write-Host "  Double-click  scripts\start_windows.bat" -ForegroundColor Cyan
Write-Host "  or run        .\scripts\start_windows.ps1" -ForegroundColor Cyan
Write-Host "`nFirst run will auto-download the Gemma 4 model (~2GB).`n"
